Users can upload or change their Profile pixture or Cover photo
goodnessaig1/TeamWork-Frontend pull request #17
Opened 2022-11-08 16:22 UTC by goodnessaig1

2022-11-08 17:26 UTC, courage173 requested changes
Please the UI issues and the additional issues here. thanks

2022-11-08 17:26 UTC, courage173 commented on src/Auth/Actions/userActions.js
> +export const UploadProfilePIx = (formData, history) =>{
what is PIx??

2022-11-08 17:26 UTC, courage173 commented on src/Auth/Actions/userActions.js
> +                const  {data}  = payload;
i don't understand this if else to check error. is the error not suppose to come in a catch block, and where is the catch block

2022-11-09 19:08 UTC, goodnessaig1 commented on src/Auth/Actions/userActions.js
> +export const UploadProfilePIx = (formData, history) =>{
I have changed it to photo now sit

2022-11-10 07:08 UTC, courage173 requested changes

2022-11-10 07:08 UTC, courage173 commented on src/Auth/Actions/userActions.js
> +                const  {data}  = payload;
goodness please update all your actions.
`
export const UploadCoverPhoto = (formData, setCoverImg, setSubmitting) =>{
    return async (dispatch) => {
            const promise =   apiRequest('PATCH', `auth/v1/cover_photo`,formData,
                {
                    headers: {
                        "Content-Type": "multipart/form-data",
                        'Accept': 'multipart/form-data',
                    },
                });
                promise.then(payload => {
                        const  {data}  = payload; 
                            toast.success('Successful', {position: toast.POSITION.TOP_RIGHT});
                            dispatch(changePictureSuccess(data))
                    }).catch((error) => {
                      toast.error('An Error occured, Please try again', {position: toast.POSITION.TOP_RIGHT});
                     })
                  
                return promise;
    }
}
`

2022-11-10 11:22 UTC, courage173 requested changes

2022-11-10 11:22 UTC, courage173 commented on src/Components/Profile/UserCoverModal.js
> +                    UploadCoverPhoto(formData, setSubmitting).then(response => {
now think about this, you don't need to pass setSubmitting you can do it inside the .then

2022-11-12 21:43 UTC, merged